### ISSUE TITLE
Duplicated code block

### ISSUE THREAD

**Issue by fbougeno** [ChloeCodesThings/chloe_flask_docker_demo#1]
I have read [your article](https://codefresh.io/blog/hello-whale-getting-started-docker-flask/). Good job and explanation.

In your app.py, you have a duplicated block:
```
if __name__ == '__main__':
    app.run(debug=True, host='0.0.0.0')
```
on line 13: 
https://github.com/ChloeCodesThings/chloe_flask_docker_demo/blob/master/web/app.py#L13

It's a minor issue, anyway.

**Comment by ChloeCodesThings** [comment]
Fixed- thank you! :)
